### ISSUE TITLE
Error: Please initialize Waigo first.

### ISSUE THREAD

**Issue by spideynn** [hiddentao/melkor#13]
OS: Windows 8.1 64-bit
NodeJS Version: v0.11.14-nightly-20140819-pre
Installed via npm install melkor -g

```
C:\Users\Spideynn\Desktop\Wiki> melkor
Error: Please initialise Waigo first
    at Object.loader.load (c:\Users\Spideynn\AppData\Roaming\npm\node_modules\melko
r\node_modules\waigo\src\loader.js:241:11)
    at Object.<anonymous> (c:\Users\Spideynn\AppData\Roaming\npm\node_modules\melko
r\node_modules\waigo\src\application.js:14:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.loader.load (C:\Users\Spideynn\AppData\Roaming\npm\node_modules\melko
r\node_modules\waigo\src\loader.js:269:10)
    at exports.init (C:\Users\Spideynn\AppData\Roaming\npm\node_modules\melkor\inde
x.js:25:22)
```

**Comment by hiddentao** [comment]
What is your startup code? (i.e. do you call `yield waigo.init()` before starting the application?)

**Comment by hiddentao** [comment]
I think this is due to how melkor currently enables the harmony ES6 features, see https://github.com/hiddentao/melkor/blob/master/bin/melkor#L1

This is clearly a UNIX-oriented method. I might be able to fix this by shifting to using v8-flags.

**Comment by hiddentao** [comment]
Fixed.
