### ISSUE TITLE
Module not found: support/underscore

### ISSUE THREAD

**Issue by noKid** [hiddentao/melkor#15]
Hello !
I was trying to use Melkor on a Windows (7, x64) machine, but ran into this error message:
```
Error: Module not found: support/underscore
    at Object.loader.load (C:\Users\dev\Desktop\wiki\node_modules\melkor\node_modules\waigo\src\loader.js:255:11)
    at Object.<anonymous> (C:\Users\dev\Desktop\wiki\node_modules\melkor\node_modules\waigo\src\application.js:14:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.loader.load (C:\Users\dev\Desktop\wiki\node_modules\melkor\node_modules\waigo\src\loader.js:269:10)
    at exports.init (C:\Users\dev\Desktop\wiki\node_modules\melkor\index.js:26:19)
```

Any Idea ?
Thx

**Comment by hiddentao** [comment]
Try doing `npm install` again, looks like `underscore` is missing.

**Comment by hiddentao** [comment]
May be related to #13

**Comment by arcandio** [comment]
I'm having an identical problem with the latest on the same platform, Win7/64. Double checked to make sure underscore was installed, even installed it where I want Melkor to run, but no luck. I sorted through the error, and I don't see any way for the `underscore.js` in `waigo/src/support` to actually find an instance of underscore as it's installed in NPM, but then again, I don't know anything about Node.js in the first place. It just looks to me like `waigo/src/application.js:13-14` is looking in the wrong place for it or something. Please advise, I'd love to have Melkor running.

**Comment by hiddentao** [comment]
It's hard for me to figure this one out since I'm running OS X. Have any other windows users managed to get it working? I'm also wondering whether this is due to use of `/` rather than `\`.

**Comment by hiddentao** [comment]
Maybe I'll should get a VM up and running for this. Will give this a crack in a couple of weeks time.
